AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless application that invokes AWS IoT SiteWise

Resources:
  SiteWiseActionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Lambda function that defines the Bedrock action group that invokes AWS IoT SiteWise
      CodeUri: lambda/
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Timeout: 30
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - iotsitewise:ListAssetModelCompositeModels
              - iotsitewise:ListActions
              - iotsitewise:ListAssociatedAssets
              - iotsitewise:DescribeAssetModelCompositeModel
              - iotsitewise:ListAssets
              - iotsitewise:GetInterpolatedAssetPropertyValues
              - iotsitewise:BatchGetAssetPropertyValueHistory
              - iotsitewise:GetAssetPropertyValue
              - iotsitewise:ListAssetModelProperties
              - iotsitewise:ExecuteQuery
              - iotsitewise:DescribeAssetModel
              - iotsitewise:DescribeAssetProperty
              - iotsitewise:DescribeAsset
              - iotsitewise:ListAssetProperties
              - iotsitewise:ListAssetModels
              - iotsitewise:DescribeAssetCompositeModel
              - iotsitewise:GetAssetPropertyAggregates
            Resource: "*"
  
  SiteWiseActionFunctionResourcePolicy:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SiteWiseActionFunction
      Action: lambda:InvokeFunction
      Principal: bedrock.amazonaws.com
      SourceArn: !Sub "arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:agent/*"

Outputs:
  SiteWiseActionFunction:
    Description: "IoT SiteWise Action Function ARN"
    Value: !GetAtt SiteWiseActionFunction.Arn
